version: '3.3'

services:
  basex:
    image:  basex/basexhttp:8.6.3 
    restart: always
    ports:
      - "1984:1984"
      - "8984:8984"

    volumes:
      - /home/bw/bverwg/docker/basex/BaseXData:/srv/BaseXData
      - /home/bw/bverwg/docker/basex/WEB-INF:/srv/BaseXWeb/WEB-INF

  # mysql:
  #   image: mysql:5.7
  #   #volumes:
  #   #  - db_data:/var/lib/mysql
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: "wordpress"
  #     MYSQL_DATABASE: "wordpress"
  #     MYSQL_USER: "wordpress"
  #     MYSQL_PASSWORD: "wordpress"
  #   ports:
  #     - "3306:3306"

  
  # solr:
  #   depends_on: 
  #     - db
  #   image: solr:alpine
  #   ports:
  #     - "8983:8983"
  #   restart: always
  #   volumes:
  #     - 'solr_data:/opt/solr/server/solr'
  #     #- '/var/solr/data/test:/opt/solr/server/solr/test'
  #   #command: 
  #     #-'solr create -c ent'
  
  apache2:
    depends_on: 
#      - mysql
      - basex
    image: php:apache
    ports:
      - "80:80"
    restart: always
    volumes:
      - '/home/bw/bverwg/docker/httpd:/var/www/html'
      

  nginxproxy:
    depends_on:
      - basex
    image: shakyshane/nginx-cors-plus
    ports:
      - 8090:80
    environment:
      - TARGET="http://basex:8984"
  
  composer:
    depends_on:
      - apache2 
    restart: "no"
    image: composer:latest
    command: install
    volumes:
      - '/home/bw/bverwg/docker/httpd:/app'

  
  # languagetool:
  #   image: silviof/docker-languagetool:latest
  #   ports:
  #     - "8010:8010"
  #   volumes:
  #     - 'db_languagetool:/ngrams'   

volumes:
    db_languagetool: {}
